In [0]:
import tensorflow as tf

In [50]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
print(dataset)
#for window_dataset in dataset:
  #print(window_dataset.numpy())
  #for val in window_dataset:
    #print(val.numpy(), end = " ")
  #print()
for x,y in dataset:
  print("x = ",x.numpy())
  print("y = ", y.numpy())

<PrefetchDataset shapes: ((None, None), (None, None)), types: (tf.int64, tf.int64)>
x =  [[5 6 7 8]
 [0 1 2 3]]
y =  [[9]
 [4]]
x =  [[4 5 6 7]
 [3 4 5 6]]
y =  [[8]
 [7]]
x =  [[2 3 4 5]
 [1 2 3 4]]
y =  [[6]
 [5]]
